#define SHADER						256 // Der Wert ist egal
#define IDS_AMBIENTVERTEXSHADER				101
#define IDS_AMBIENTFRAGMENTSHADER			102
#define IDS_COMPOSITEVERTEXSHADER			104
#define IDS_COMPOSITEFRAGMENTSHADER			105
#define IDS_FILLBUFFERVERTEXSHADER			107
#define IDS_FILLBUFFERFRAGMENTSHADER		108
