#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <memory>
#include <string>
#include <hash_map>
#include <hash_set>
#include <map>
#include <list>
#include <iostream>
#include <fstream>
#include <vector>
#include <stdarg.h>
#include <stdio.h>
#include <assert.h>